### ISSUE TITLE
Error: could not get uid/gid

### ISSUE THREAD

**Issue by throrin19** [mgibeau/gitlab-npm-audit-parser#5]
Hello, When I try to run this command on my gitlab-runners, I have this error : 

```
$ npm audit --json | npx gitlab-npm-audit-parser -o gl-dependency-scanning.json
Error: could not get uid/gid
[ 'nobody', 0 ]

    at /usr/lib/node_modules/npm/node_modules/uid-number/uid-number.js:37:16
    at ChildProcess.exithandler (child_process.js:288:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
TypeError: Cannot read property 'loaded' of undefined
    at exit (/usr/lib/node_modules/npm/lib/utils/error-handler.js:98:27)
    at errorHandler (/usr/lib/node_modules/npm/lib/utils/error-handler.js:216:3)
    at /usr/lib/node_modules/npm/bin/npm-cli.js:77:20
    at cb (/usr/lib/node_modules/npm/lib/npm.js:225:22)
    at /usr/lib/node_modules/npm/lib/npm.js:263:24
    at /usr/lib/node_modules/npm/lib/config/core.js:83:7
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/npm/lib/config/core.js:82:13
    at f (/usr/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at afterExtras (/usr/lib/node_modules/npm/lib/config/core.js:173:20)
/usr/lib/node_modules/npm/lib/utils/error-handler.js:98
  var doExit = npm.config.loaded ? npm.config.get('_exit') : true
                          ^

TypeError: Cannot read property 'loaded' of undefined
    at exit (/usr/lib/node_modules/npm/lib/utils/error-handler.js:98:27)
    at process.errorHandler (/usr/lib/node_modules/npm/lib/utils/error-handler.js:216:3)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process._fatalException (bootstrap_node.js:391:26)
Install for gitlab-npm-audit-parser@latest failed with code 7
Uploading artifacts...
WARNING: gl-dependency-scanning.json: no matching files 
ERROR: No files to upload                          
ERROR: Job failed: exit code 7
```

For information, I run gitlab-runner version 11.10 with docker-machines and amazonec2 driver (with amazon spots instances)

**Comment by throrin19** [comment]
Ok, after research, the problem is with NPM, AWS and docker, not with your package : https://github.com/npm/uid-number/issues/3
