### ISSUE TITLE
JSON parse error when audit json larger than 64K

### ISSUE THREAD

**Issue by bangbang93** [mgibeau/gitlab-npm-audit-parser#6]
```
undefined:1523
        ,},
         ^

SyntaxError: Unexpected token } in JSON at position 65537
    at JSON.parse (<anonymous>)
    at convert (/Users/bangbang93/.npm/_npx/43448/lib/node_modules/gitlab-npm-audit-parser/lib/convert.js:12:21)
    at Socket.<anonymous> (/Users/bangbang93/.npm/_npx/43448/lib/node_modules/gitlab-npm-audit-parser/parse.js:26:20)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
the output json is 597KB

I used to think it was related to the nodejs, but I can't reproduce in pure node event
```typescript
const chunks: string[] = []
process.stdin.setEncoding('utf8')
process.stdin.on('data', (chunk: string) => {
  chunks.push(chunk)
})

process.stdin.once('end', () => {
  const data = chunks.join('')
  // const data = Buffer.concat(chunks).toString()
  JSON.parse(data)
})
```

**Comment by bangbang93** [comment]
OK I got it
The joined JSON has a wrong comma
![image](https://user-images.githubusercontent.com/3430784/67538290-61461b80-f711-11e9-8e3a-256f7d03df00.png)

**Comment by mgibeau** [comment]
Fix has been merged and released: https://www.npmjs.com/package/gitlab-npm-audit-parser
